<?php

namespace AchatBundle\Repository;

use AchatBundle\Entity\Commande;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Commande|null find($id, $lockMode = null, $lockVersion = null)
 * @method Commande|null findOneBy(array $criteria, array $orderBy = null)
 * @method Commande[]    findAll()
 * @method Commande[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Commande::class);
    }
    public function findPremiumByChargeId($chargeId)
    {
        return $this
            ->createQueryBuilder('u')
            ->andWhere('u.premium = :premium')
            ->andWhere('u.chargeId = :chargeId')
            ->setParameters([
                'premium' => true,
                'chargeId' => $chargeId,
            ])
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findOneBySomeField($value): ?Commande
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.idOrder = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }
}
